name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-foundry-zksync:
    runs-on: ubuntu-latest
    steps:
      - name: "Install foundry zksync"
        uses: brotherlymite/foundry-toolchain@v1.0
