name: Main workflow

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-foundry-zksync:
    runs-on: ubuntu-latest
    steps:
      - name: "Install foundry zksync"
        uses: brotherlymite/foundry-toolchain@v1.1

      - name: Forge version
        run:
          forge --version | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g' | tee /tmp/foundry_version
